### ISSUE TITLE
bug: The label interferes to the progressbar

### ISSUE THREAD

**Issue by ghost** [rafaelhlima/remove_blank_cells#1]
Win10, Libre 7.2.2.2 
Version: 7.2.2.2 (x64) / LibreOffice Community
Build ID: 02b2acce88a210515b4a5bb2e46cbfb63fe97d56
CPU threads: 8; OS: Windows 10.0 Build 17763; UI render: Skia/Raster; VCL: win
Locale: cs-CZ (cs_CZ); UI: cs-CZ
Calc: CL

![label-removing-blank-rows](https://user-images.githubusercontent.com/61148366/138504453-0016dbfa-1a38-4d17-9a4d-0c36421052ee.png)

It is easy to fix it, decrease about 2pt the y-position of the label :-)

**Comment by rafaelhlima** [comment]
Hi @KamilLanda this issue is happening on Windows. I had run most tests on Linux only.
I guess I can come up with a solution that will work on both operating systems.

**Comment by rafaelhlima** [comment]
Hi, this bug has been fixed in the newest v0.10.0 release.
