### ISSUE TITLE
Add Arabic Translation

### ISSUE THREAD

**Issue by RiyadhT** [rafaelhlima/remove_blank_cells#11]
This is the Arabic translation po file.
[rb_strings_ar.zip](https://github.com/rafaelhlima/remove_blank_cells/files/8309399/rb_strings_ar.zip)

**Comment by rafaelhlima** [comment]
Hi @RiyadhT thanks for your contribution. I'll check your file and add it to the code base.

Expect it to be available in the upcoming release 0.10.1 of the extension.

**Comment by rafaelhlima** [comment]
@RiyadhT the Arabic translation is now available in the main branch through commit 8ea229e.
