### ISSUE TITLE
bug: No centered dialogs

### ISSUE THREAD

**Issue by ghost** [rafaelhlima/remove_blank_cells#2]
The dialogs aren't centered. 

Win10, Libre 7.2.2.2 
Version: 7.2.2.2 (x64) / LibreOffice Community
Build ID: 02b2acce88a210515b4a5bb2e46cbfb63fe97d56
CPU threads: 8; OS: Windows 10.0 Build 17763; UI render: Skia/Raster; VCL: win
Locale: cs-CZ (cs_CZ); UI: cs-CZ
Calc: CL

![dialog-not-centered](https://user-images.githubusercontent.com/61148366/138504620-e45a8b3e-6ba6-4146-803b-df588e84add0.png)

It is possible to fix it with the method setPosSize in the function CenterDialog. And also to calculate with the oDlg Sizes and not with the Model Sizes. 
```
newPosX = (winWidth - oDlg.OutputSize.Width) / 2
newPosY = (winHeight - oDlg.OutputSize.Height) / 2
oDlg.setPosSize(newPosX, newPosY, 0, 0, com.sun.star.awt.PosSize.POS)
```

But next problem is if the oRBDlg is visible and the Progressbar too. 
![progressbar-not-centered](https://user-images.githubusercontent.com/61148366/138504685-33a5c0c1-9c1a-49e7-8abd-92d3ded8daf2.png)

In my computer it seems the ProgressBar dialog is positioned relatively from the previous showed dialog (oRBDlg) and not absolutely from the Calc window (maybe it is the bug of the LibreOffice). So I fix it by hide the oRBDlg and set its position to the 0,0 in the functions RB_RemoveEmptyRows & RB_RemoveEmptyColumns. 

```
oRBDlg.Visible=false 'hide the RBdialog
oRBDlg.setPosSize(0, 0, 0, 0, com.sun.star.awt.PosSize.POS) 'set RBdialog to the position 0,0
CenterDialog(oProgDlg)
oProgDlg.SetVisible(True)
```

![fix-progressbar](https://user-images.githubusercontent.com/61148366/138504787-b207b778-42e9-426a-a8a5-55972d870ab1.png)

**Comment by rafaelhlima** [comment]
Hi, this bug has been fixed in the newest v0.10.0 release.
