### ISSUE TITLE
Test of the empty rows or the empty columns for the matrix

### ISSUE THREAD

**Issue by ghost** [rafaelhlima/remove_blank_cells#3]
What to add the test of the empty rows and the empty columns in the matrix? 
Because if you have only empty rows in the matrix (or only empty columns), then the main dialog is unneeded -> and you can automatically delete only empty rows or only empty columns. 
So the main dialog is needy only if there are empty rows and also empty columns in the matrix.  

![test-empties-for-matrix](https://user-images.githubusercontent.com/61148366/138594118-d5c2a0df-397b-4148-98c8-df336305a055.png)

**Comment by rafaelhlima** [comment]
Hi @KamilLanda the point you made is valid. While I myself was using the extension, I came across many situations where I had only empty rows and the dialog showed up although it wasn't really necessary.

I will add this new behavior for the upcoming version.

**Comment by Mami16glcn** [comment]
@KamilLanda @rafaelhlima

**Comment by rafaelhlima** [comment]
Hi, this bug has been fixed in the newest v0.10.0 release.

It is now possible to launch Remove Blank Rows or Remove Blank Columns directly with keyboard shortcuts or menu entries, which will perform the operations without showing the dialog.
