### ISSUE TITLE
3-character ellipses `...`  to 1-character ellipses `…`

### ISSUE THREAD

**Issue by ovari** [rafaelhlima/remove_blank_cells#4]
Should the strings with 3-character ellipses `...` be changed to 1-character ellipses `…`?

Thank you

Can we provide hu (Hungarian - magyar) translation? Will this be available with [Weblate](https://hosted.weblate.org/)?

Thank you once again

**Comment by rafaelhlima** [comment]
Hi @ovari, It does make sense to replace "..." bu the ellipsis character. Will do so in the next release.

As for the translation, I am planning to provide a ".pot" file for translation. I'll let you know here when this is done.

**Comment by rafaelhlima** [comment]
Hi, this bug has been fixed in the newest v0.10.0 release.

**Comment by ovari** [comment]
> As for the translation, I am planning to provide a ".pot" file for translation. I'll let you know here when this is done.

Does another issue need to be created regarding translations on Weblate? Or will you be adding a hu (Hungarian - magyar) pot file which we can fill in the Hungarian translations?

Thank you
