### ISSUE TITLE
Add support for Swedish

### ISSUE THREAD

**Issue by Umeaboy** [rafaelhlima/remove_blank_cells#6]
Here's the po since GitHub won't allow uploading of po-files: https://drive.google.com/file/d/1poqm4c6P27-J_XuGsvMIU36yphpmpw__/view?usp=sharing

Signed-off-by: Kristoffer Grundström <swedishsailfishosuser@tutanota.com>

**Comment by rafaelhlima** [comment]
Hi Kristoffer, thank so much for this contribution.

I noticed you did not add your name in the "Last-Translator" field of the .po file. If you'd like, I can add it for you.

Your translation will be available in the upcoming v0.10.1 release.

**Comment by Umeaboy** [comment]
> Hi Kristoffer, thank so much for this contribution.

You're welcome.

> I noticed you did not add your name in the "Last-Translator" field of the .po file. If you'd like, I can add it for you.

Sure, go right ahead.
