### ISSUE TITLE
Add support for French

### ISSUE THREAD

**Issue by LibreOfficiant** [rafaelhlima/remove_blank_cells#8]
Actually I'm taking care

**Comment by rafaelhlima** [comment]
Hi Allain, thanks for taking care of this. Having a French translation will be great.

You can submit it either as a pull request or attach the translated po to this issue.

**Comment by LibreOfficiant** [comment]
[rb_strings.fr_FR.po.txt](https://github.com/rafaelhlima/remove_blank_cells/files/8316309/rb_strings.fr_FR.po.txt)
[rb_strings.fr_FR.mo.txt](https://github.com/rafaelhlima/remove_blank_cells/files/8316310/rb_strings.fr_FR.mo.txt)

**Comment by rafaelhlima** [comment]
Thank you for the contribution.

The French translation has been added to the main branch by commit 142c210.
